### ISSUE TITLE
pygradboost | error

### ISSUE THREAD

**Issue by LPecht** [mdroste/stata-pylearn#2]
. pylearn, setup
Looking for Python module pandas...
  The module pandas was found.
Looking for Python module numpy...
  The module numpy was found.
Looking for Python module scikit-learn...
  The module scikit-learn was found.
Done! All prerequisites for pylearn are installed.

. webuse iris, clear
(Iris data)
. pygradboost iris seplen sepwid petlen petwid, type(classify) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 74, in run_gradboost
TypeError: __init__() got an unexpected keyword argument 'ccp_alpha'
r(7102);

**Comment by mdroste** [comment]
It turns out this error is caused by an older version of scikit-learn. The ccp_alpha parameter was added to the gradient booster classes in scikit-learn 0.23 - you get this error if you have scikti-learn 0.22 or below.

In the near future, I'm going to handle this more flexibly, checking to see what version of scikit-learn you have, automatically upgrading to the latest version otherwise. But pygradboost should work for you now! Just run 'pylearn, upgrade' to upgrade to the version I just pushed.

**Comment by LPecht** [comment]
now it is working. 

My personal advice is not to automatically upgrading scikti-learn to the latest. It is the kind of fundamental package which hundred on others depend on ( python dependency hell ). Just expose your minimum requirements and let the user to decide upon. thks
